name: yamller
description: A library for generate dart file from yaml.
version: 0.0.2
homepage: https://github.com/laiiihz/yamller

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
dependencies:
  args: ^2.2.0
  code_builder: ^4.1.0
  dart_style: ^2.0.3
  recase: ^4.0.0
  yaml: ^3.1.0
  path: ^1.8.0

executables:
  yamller:
